ServerName apache

LoadModule rewrite_module /usr/local/apache2/modules/mod_rewrite.so

LoadModule deflate_module /usr/local/apache2/modules/mod_deflate.so
LoadModule proxy_module /usr/local/apache2/modules/mod_proxy.so
LoadModule proxy_fcgi_module /usr/local/apache2/modules/mod_proxy_fcgi.so

<VirtualHost *:80>

    # Proxy .php requests to port 9000 of the php-fpm container
    ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://php:9000/src/$1
    DocumentRoot /src/
    <Directory /src/>
        DirectoryIndex index.php
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 common

</VirtualHost>
