version: "3.1"

services:

  php:
    container_name: ${PROJECT_NAME}_php_${VERSION_ID}
    build:
      context: ./docker/php
      args:
        - XDEBUG=${XDEBUG}
        - COMPOSER=${COMPOSER}
    ports:
      - 9000:9000
    volumes:
      - ./src:/src:cached
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./logs/php:/usr/local/etc/php/logs
    environment:
      WEBAPP_URL: ${WEBAPP_URL}
      TIME_ZONE: ${TIME_ZONE}
      DB_HOST: db:${DB_PORT_EXPOSED}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
 
  web:
    container_name: ${PROJECT_NAME}_web_${VERSION_ID}
    build:
      context: ./docker/apache
    ports:
      - ${HTTP_PORT_EXPOSED}:80
      # - ${HTTPS_PORT_EXPOSED}:443
    volumes:
      - ./src:/src:ro
      - ./docker/apache/webapp.conf:/usr/local/apache2/conf/webapp.conf:ro
      # - ./docker/apache/certs:/etc/apache/certs:ro
      - ./logs/web:/var/log/apache2
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
    depends_on:
      - php

  db:
    container_name: ${PROJECT_NAME}_db_${VERSION_ID}
    build:
      context: ./docker/mariadb
    ports:
      - ${DB_PORT_EXPOSED}:3306
    volumes:
      - ./db:/var/lib/mysql
      # - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      - ./logs/db:/var/log/mysql
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

